FROM node:14-alpine3.10
LABEL version="1.0"
LABEL description="Development image for the library MERN API"
WORKDIR /app
# COPY ["package.json", "package-lock.json*", ]
COPY /package*.json /app/
RUN npm install
COPY . .
EXPOSE 5000
CMD ["npm", "start"]

